/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hospital.project;


import java.awt.Menu;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class testFrame extends javax.swing.JFrame {

    /**
     * Creates new form testFrame
     */
    public testFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        IDTestL = new javax.swing.JLabel();
        nameTestL = new javax.swing.JLabel();
        dateTestL = new javax.swing.JLabel();
        timeTestL = new javax.swing.JLabel();
        IDTestT = new javax.swing.JTextField();
        nameTestT = new javax.swing.JTextField();
        dateTestT = new javax.swing.JTextField();
        timeTestT = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        testTable = new javax.swing.JTable();
        insertTestB = new javax.swing.JButton();
        selectTestB = new javax.swing.JButton();
        deleteTestB = new javax.swing.JButton();
        homeB = new javax.swing.JButton();
        ubdateTestB = new javax.swing.JButton();
        resultTestL = new javax.swing.JLabel();
        resultTestT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Test");
        setLocation(new java.awt.Point(360, 80));
        setPreferredSize(new java.awt.Dimension(868, 700));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        IDTestL.setText("ID");

        nameTestL.setText("name");

        dateTestL.setText("date");

        timeTestL.setText("time");

        IDTestT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTestTActionPerformed(evt);
            }
        });

        nameTestT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTestTActionPerformed(evt);
            }
        });

        timeTestT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTestTActionPerformed(evt);
            }
        });

        testTable.setBackground(new java.awt.Color(242, 240, 240));
        testTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "name", "date", "time", "result"
            }
        ));
        jScrollPane1.setViewportView(testTable);

        insertTestB.setText("Insert");
        insertTestB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertTestBActionPerformed(evt);
            }
        });

        selectTestB.setText("Select");
        selectTestB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectTestBActionPerformed(evt);
            }
        });

        deleteTestB.setText("Delete");
        deleteTestB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTestBActionPerformed(evt);
            }
        });

        homeB.setText("Home");
        homeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBActionPerformed(evt);
            }
        });

        ubdateTestB.setText("Update");
        ubdateTestB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubdateTestBActionPerformed(evt);
            }
        });

        resultTestL.setText("result");

        resultTestT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultTestTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(homeB)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeTestL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(resultTestL)
                                    .addComponent(dateTestL)
                                    .addComponent(nameTestL)
                                    .addComponent(IDTestL)))
                            .addComponent(insertTestB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(selectTestB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(deleteTestB, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(ubdateTestB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(resultTestT)
                                    .addComponent(nameTestT, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                    .addComponent(IDTestT)
                                    .addComponent(dateTestT)
                                    .addComponent(timeTestT))))
                        .addGap(0, 30, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IDTestL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(IDTestT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(homeB, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTestL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(nameTestT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTestL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTestT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeTestT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeTestL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultTestL, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultTestT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectTestB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insertTestB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteTestB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ubdateTestB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IDTestTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDTestTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDTestTActionPerformed

    private void nameTestTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTestTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTestTActionPerformed

    private void timeTestTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTestTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTestTActionPerformed

    private void homeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBActionPerformed
        if (evt.getSource() == homeB)
        {
            home h = new home ();
            this.setVisible(false);
            h.setVisible(true);
        }
    }//GEN-LAST:event_homeBActionPerformed

    private void resultTestTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultTestTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resultTestTActionPerformed

    private void selectTestBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTestBActionPerformed
              try {
            ((DefaultTableModel)testTable.getModel()).setNumRows(0);
        connection c = new connection();
            String query = "Select * from test";
            Statement st = c.con.createStatement();
            ResultSet rs = st.executeQuery(query);
           
       DefaultTableModel model = (DefaultTableModel) testTable.getModel();
        Object []row = new Object[5];
 
            while (rs.next())
            {
                row[0] = rs.getString("ID");
                row[1] = rs.getString("name");
                row[2] = rs.getString("date");
                row[3] = rs.getString("time");
                row[4] = rs.getString("result");
                          model.addRow(row);

            }
        } catch (SQLException ex) {
            
            Logger.getLogger(doctorFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_selectTestBActionPerformed

    private void insertTestBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertTestBActionPerformed
                try {      
          connection c = new connection();
         
         String sql = " insert into test values(? , ? , ? , ? , ?);";
         PreparedStatement pstm = c.con.prepareStatement(sql);
         pstm.setString(1 ,IDTestT.getText() );
         pstm.setString(2 , nameTestT.getText());
         pstm.setString(3 , dateTestT.getText() );
         pstm.setString(4 , timeTestT.getText() );
         pstm.setString(5 , resultTestT.getText() );
            
         
         pstm.executeUpdate();
         
         //JOptionPane.showMessageDialog(null,"doctor added Successfully");
         c.con.close();

         
        } catch ( SQLException ex) {

            JOptionPane.showMessageDialog(null,ex);
        }
        catch(NumberFormatException e){
              JOptionPane.showMessageDialog(null,"Type a right values");
        }  
    }//GEN-LAST:event_insertTestBActionPerformed

    private void deleteTestBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTestBActionPerformed
         try {
            connection c = new connection();
            String sql = " Delete from test where ID = ?;";
            PreparedStatement pstm = c.con.prepareStatement(sql);
            pstm.setString(1 , IDTestT.getText() );
            
            pstm.executeUpdate();
            c.con.close();
           // JOptionPane.showMessageDialog(null, "Book Deleted Successfully");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_deleteTestBActionPerformed

    private void ubdateTestBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubdateTestBActionPerformed
         try {
            connection c = new connection();
            //String sql = " update doctor set first name = " +firstNameT.getText()+ ", last name = " + lastNameT.getText() + ", specilization = " + specilizationT.getText()+ "where SSN = " +SSNT.getText()+";" ;
           String sql = " update test set name = ?, date = ?, time = ?, result = ? where ID = ?;" ;

         PreparedStatement pstm = c.con.prepareStatement(sql);
         pstm.setString(5 ,IDTestT.getText() );
         pstm.setString(1 , nameTestT.getText());
         pstm.setString(2 , dateTestT.getText() );
         pstm.setString(3 , timeTestT.getText() );
         pstm.setString(4 , resultTestT.getText() );
            

            pstm.executeUpdate();
            
            c.con.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ubdateTestBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDTestL;
    private javax.swing.JTextField IDTestT;
    private javax.swing.JLabel dateTestL;
    private javax.swing.JTextField dateTestT;
    private javax.swing.JButton deleteTestB;
    private javax.swing.JButton homeB;
    private javax.swing.JButton insertTestB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameTestL;
    private javax.swing.JTextField nameTestT;
    private javax.swing.JLabel resultTestL;
    private javax.swing.JTextField resultTestT;
    private javax.swing.JButton selectTestB;
    private javax.swing.JTable testTable;
    private javax.swing.JLabel timeTestL;
    private javax.swing.JTextField timeTestT;
    private javax.swing.JButton ubdateTestB;
    // End of variables declaration//GEN-END:variables
}
